---
- name: Hello World AWX project
  hosts: all 
  tasks: 
  - name: Hello World AWX tasks
    debug:
      msg: "{{var_1 var_2 var_3}}, it works!"   
  - name: Merged vars in the git tasks
    debug:
      msg: "{{var_1 var_4}}!"   
